ScamBet/Controllers/LiveGameController.cs
using Microsoft.AspNetCore.Mvc;

namespace ScamBet.Controllers
{
    public class LiveGameController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ScamBet/Controllers/MatchController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScamBet.Entities;

namespace ScamBet.Controllers
{
    [Authorize]
    public class MatchController : Controller
    {
        private readonly BookmacherDBContext _context;

        public MatchController(BookmacherDBContext context)
        {
            _context = context;
        }

        // GET: Match
        public async Task<IActionResult> Index()
        {
            var matches = await _context.Matches.Include(m => m.Team1).Include(m => m.Team2).ToListAsync();

            return View(matches);
        }

        // GET: Match/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches.FindAsync(id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }


        // GET: Match/Create
        public IActionResult Create()
        {
            ViewData["Team1"] = new SelectList(_context.Teams, "team_ID", "name");
            ViewData["Team2"] = new SelectList(_context.Teams, "team_ID", "name");
            return View();
        }

        // POST: Match/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("match_ID,team1_ID,team2_ID,time,team1_goals,team2_goals,isPlayed,winner_ID")] Match match)
        {
            if (ModelState.IsValid)
            {
                AssignWinner(match);
                _context.Add(match);
                match.time = DateTime.Now;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Team1"] = new SelectList(_context.Teams, "team_ID", "name", match.team1_ID);
            ViewData["Team2"] = new SelectList(_context.Teams, "team_ID", "name", match.team2_ID);
            return View(match);
        }

        // GET: Match/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches.FindAsync(id);
            if (match == null)
            {
                return NotFound();
            }
            ViewData["Team1"] = new SelectList(_context.Teams, "team_ID", "name", match.team1_ID);
            ViewData["Team2"] = new SelectList(_context.Teams, "team_ID", "name", match.team2_ID);
            return View(match);
        }

        // POST: Match/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("match_ID,team1_ID,team2_ID,time,team1_goals,team2_goals,isPlayed,winner_ID")] Match match)
        {
            if (id != match.match_ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    AssignWinner(match);
                    _context.Update(match);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatchExists(match.match_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Team1"] = new SelectList(_context.Teams, "team_ID", "name", match.team1_ID);
            ViewData["Team2"] = new SelectList(_context.Teams, "team_ID", "name", match.team2_ID);
            return View(match);
        }

        // GET: Match/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches.FirstOrDefaultAsync(m => m.match_ID == id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }

        // POST: Match/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var match = await _context.Matches.FindAsync(id);
            _context.Matches.Remove(match);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MatchExists(int id)
        {
            return _context.Matches.Any(e => e.match_ID == id);
        }

        private void AssignWinner(Match match)
        {
            if (match.team1_goals > match.team2_goals)
            {
                match.winner_ID = match.team1_ID;
            }
            else if (match.team2_goals > match.team1_goals)
            {
                match.winner_ID = match.team2_ID;
            }
            else
            {
                match.winner_ID = 0;
            }
        }
    }
}

ScamBet/Controllers/RuletteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScamBet.Entities;
using ScamBet.Models;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ScamBet.Controllers
{
    [Authorize]
    public class RouletteController : Controller
    {
        private readonly BookmacherDBContext _context;

        public RouletteController(BookmacherDBContext context)
        {
            _context = context;
        }

        // GET: Roulette/Index
            public async Task<IActionResult> Index()
            {
                return View();
            }
        
        // GET: Roulette/Play
        public async Task<IActionResult> Play()
        {
            var recentResults = await _context.Roulette
                                           .OrderByDescending(b => b.betTime_r)
                                           .Take(10)
                                           .ToListAsync();
            ViewBag.RecentBets = recentResults;
            return View();
        }

        // POST: Roulette/PlaceBet
        public async Task<IActionResult> PlaceBet(string betType, string betValue, double betAmount)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var account = await _context.Accounts.FindAsync(userId);

            if (account == null || betAmount <= 0 || account.acc_balance < betAmount)
            {
                return BadRequest("Invalid bet amount or insufficient balance.");
            }

            ViewBag.BetAmount = betAmount;

            var rouletteResult = GenerateRouletteResult();
            bool isWin = DetermineWin(betType, betValue, rouletteResult);

            double winnings = 0;
            if (isWin)
            {
                winnings = (betAmount * GetMultiplier(betType));
                account.acc_balance -= betAmount;
                account.acc_balance += winnings;
                account.TotalWinnings += winnings - betAmount;
            }
            else
            {
                account.acc_balance -= betAmount;
            }

            var bet = new Roulette
            {
                user_ID = userId,
                betType_r = betType,
                betValue_r = betValue,
                betAmount_r = betAmount,
                betTime_r = DateTime.Now,
                isWin_r = isWin,
                result_r = rouletteResult
            };

            _context.Roulette.Add(bet);
            await _context.SaveChangesAsync();

            ViewBag.RouletteResult = rouletteResult;
            ViewBag.IsWin = isWin;
            ViewBag.Winnings = winnings;
            ViewBag.Balance = account.acc_balance;
            ViewBag.BetAmount = betAmount;

            var recentResults = await _context.Roulette
                                           .OrderByDescending(b => b.betTime_r)
                                           .Take(10)
                                           .ToListAsync();
            ViewBag.RecentBets = recentResults;

            return View("Play");
        }

        // POST:Roulette/RepeatBet
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RepeatBet()
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var lastBet = await _context.Roulette
                                        .Where(b => b.user_ID == userId)
                                        .OrderByDescending(b => b.betTime_r)
                                        .FirstOrDefaultAsync();

            if (lastBet == null)
            {
                return BadRequest("No previous bet to repeat.");
            }

            return await PlaceBet(lastBet.betType_r, lastBet.betValue_r, lastBet.betAmount_r);
        }

        private string GenerateRouletteResult()
        {
            var random = new Random();
            int number = random.Next(0, 37);
            string color = "";

            switch (number)
            {
                case 0:
                    color = "green";
                    break;
                case int n when (n >= 1 && n <= 10) || (n >= 19 && n <= 28):
                    color = n % 2 == 0 ? "black" : "red";
                    break;
                case int n when (n >= 11 && n <= 18) || (n >= 29 && n <= 36):
                    color = n % 2 == 0 ? "red" : "black";
                    break;
            }

            return $"{number}:{color}";
        }

        private bool DetermineWin(string betType, string betValue, string rouletteResult)
        {
            var resultParts = rouletteResult.Split(':');
            var number = int.Parse(resultParts[0]);
            var color = resultParts[1];

            if (betType == "color" && betValue == color)
            {
                return true;
            }

            if (betType == "number" && betValue == number.ToString())
            {
                return true;
            }

            if (betType == "odd_even" && betValue == (number % 2 == 0 ? "even" : "odd"))
            {
                return true;
            }

            if (betType == "dozen" && ((betValue == "1st" && number >= 1 && number <= 12) ||
                                       (betValue == "2nd" && number >= 13 && number <= 24) ||
                                       (betValue == "3rd" && number >= 25 && number <= 36)))
            {
                return true;
            }

            if (betType == "half" && ((betValue == "1-18" && number >= 1 && number <= 18) ||
                                      (betValue == "19-36" && number >= 19 && number <= 36)))
            {
                return true;
            }

            if (betType == "row" && ((betValue == "1st" && number % 3 == 1) ||
                                     (betValue == "2nd" && number % 3 == 2) ||
                                     (betValue == "3rd" && number % 3 == 0)))
            {
                return true;
            }

            return false;
        }

        private double GetMultiplier(string betType)
        {
            return betType switch
            {
                "number" => 35,
                "color" => 2,
                "odd_even" => 2,
                "dozen" => 3,
                "half" => 2,
                "row" => 3,
                _ => 1
            };
        }
        
    }
}

ScamBet/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using ScamBet.Entities;

namespace ScamBet.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {
        private readonly BookmacherDBContext _context;

        public TeamController(BookmacherDBContext context)
        {
            _context = context;
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            return View(await _context.Teams.ToListAsync());
        }

        // GET: Team/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .FirstOrDefaultAsync(m => m.team_ID == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Team/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Team/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("team_ID,name,wins,draws,loses")] Team team)
        {
            team.points = team.wins * 2 + team.draws;
            if (ModelState.IsValid)
            {
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Team/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Team/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("team_ID,name,wins,draws,loses")] Team team)
        {
            if (id != team.team_ID)
            {
                return NotFound();
            }

            team.points = team.wins * 2 + team.draws;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.team_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Team/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .FirstOrDefaultAsync(m => m.team_ID == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Team/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = _context.Teams.Find(id);
            _context.Teams.Remove(team);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.team_ID == id);
        }
    }
}

ScamBet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScamBet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>

    @if (User.Identity.IsAuthenticated)
    {

        <div id="sessionTimer">Czas sesji: 10:00</div>
        <script>
            var sessionTimer = document.getElementById('sessionTimer');
            var sessionTimeInSeconds = 10 * 60;

            function updateSessionTimer() {
                var minutes = Math.floor(sessionTimeInSeconds / 60);
                var seconds = sessionTimeInSeconds % 60;
                sessionTimer.textContent = 'Czas sesji: ' + minutes.toString().padStart(2, '0') + ':' + seconds.toString().padStart(2, '0');

                sessionTimeInSeconds--;

                if (sessionTimeInSeconds < 0) {
                    window.location.href = '/Home/Login';
                }
            }

            setInterval(updateSessionTimer, 1000);
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.18/signalr.min.js"></script>
        
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><strong>ScamBet</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 move-to-right">
                       
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="AdminIndex">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Index">Accounts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Team" asp-action="Index">Teams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Match" asp-action="Index">Match</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="TotalWinnings">UserData</a>
                            </li>
                        }
                        else if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="UserIndex">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="LiveGame" asp-action="Index">LiveGame</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Roulette" asp-action="Play">Roulette</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Coinflip" asp-action="Play">Coinflip</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="TotalWinnings">Hall of Fame</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav mr-auto justify-content-end">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="navbar-toggler-icon"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                                @if (User.IsInRole("User"))
                                {
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="MyAccount">My Account</a></li>
                                    <li><a class="dropdown-item" asp-controller="Home" asp-action="History">History</a></li>
                                    <li><a class="dropdown-item" asp-controller="Home" asp-action="Deposit">Deposit</a></li>
                                    <li><a class="dropdown-item" asp-controller="Home" asp-action="Withdraw">Withdraw</a></li>
                                }
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="Logout">Log Out</a></li>
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    }
    

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <audio id="backgroundMusic" loop>
        <source src="/audio/backgroundmusic.mp3" type="audio/mpeg">
        Play this for better efficiency
    </audio>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var audio = document.getElementById('backgroundMusic');
            var playPosition = sessionStorage.getItem('audioPosition') || 0;

            audio.currentTime = playPosition;
            audio.play();

            audio.addEventListener('timeupdate', function () {
                sessionStorage.setItem('audioPosition', audio.currentTime);
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>